{% set name = "neqsim" %}
{% set version = "3.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 84cbb714d2471a135319e02778894e604268e511a5a657bec90ea8be6c4ed4ef

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - pip
    - poetry-core
  run:
    - python >={{ python_min }}
    - jpype1 >=1.5.0
    - numpy >1.25.2
    - pandas >=2.0.3
    - openjdk >=11

test:
  imports:
    - neqsim
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Equinor/neqsim-python
  summary: NeqSim is a tool for thermodynamic and process calculations
  description: |
    NeqSim Python is a Python interface to the NeqSim Java library for 
    estimation of fluid behavior and process design for oil and gas production.
    It provides toolboxes like thermoTools and processTools to streamline 
    the use of NeqSim in Python.
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  doc_url: https://github.com/equinor/neqsim-python/wiki
  dev_url: https://github.com/Equinor/neqsim-python

extra:
  recipe-maintainers:
    - EvenSol
